In [1]:
import numpy as np

y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])

In [3]:
def mae(y_true,y_predicticed):
    total_error= 0
    for yt,yp in zip(y_true,y_predicticed):
        total_error+= abs(yt-yp)
    print("total_error",total_error)
    mae = total_error/len(y_true)
    return mae

In [4]:
mae(y_true,y_pred)

total_error 2.5


0.5

In [7]:
# we can do this as well

print(np.abs(y_true - y_pred))
np.mean( np.abs(y_true-y_pred) )

[0.7 0.3 1.  0.  0.5]


0.5

In [8]:
def mse(y_true,y_predicticed):
    total_error= 0
    for yt,yp in zip(y_true,y_predicticed):
        total_error+= (yt-yp)**2
    print("total_error",total_error)
    mse = total_error/len(y_true)
    return mse

In [9]:
mse(y_true,y_pred)

total_error 1.83


0.366

In [41]:
np.mean((y_true-y_pred)**2)

0.366

In [12]:
np.log(0.000001)

-13.815510557964274

In [14]:
epsilon = 1e-15

In [15]:
y_pred

array([1, 1, 0, 0, 1])

In [32]:
y_pred_new = [ max(i,epsilon)  for i in y_pred]
y_pred_new = [ min(i,1-epsilon)  for i in y_pred_new]
y_pred_new = np.array(y_pred_new)
y_pred_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [33]:
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [34]:
- np.mean(
        y_true*np.log(y_pred_new) + \
        (1-y_true)*np.log(
            1-y_pred_new
            )
    )

17.2696280766844

In [39]:
def log_loss(y_true,y_predicted):
    epsilon = 1e-15
    y_pred_new = [ max(i,epsilon)  for i in y_predicted]
    y_pred_new = [ min(i,1-epsilon)  for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return - np.mean(
        y_true*np.log(y_pred_new) + (1-y_true)*np.log(1-y_pred_new)
    )

In [40]:
log_loss(y_true,y_pred)

17.2696280766844